#!/bin/bash

if [ -d "./examples/iq_samples_mat" ]; then
    echo "Removing iq_samples_mat directory ..."
    rm -rf "./examples/iq_samples_mat"
else
    echo "iq_samples_mat directory does not exist"
fi

if [ -d "./examples/iq_samples_fourier" ]; then
    echo "Removing iq_samples_fourier directory ..."
    rm -rf "./examples/iq_samples_fourier"
else
    echo "iq_samples_fourier directory does not exist"
fi

if [ -d "./examples/iq_samples_sigmf" ]; then
    echo "Removing iq_samples_sigmf directory ..."
    rm -rf "./examples/iq_samples_sigmf"
else
    echo "iq_samples_sigmf directory does not exist"
fi

if [ -d "build" ]; then
    echo "Removing build directory ..."
    rm -rf build
else
    echo "build directory does not exist"
fi

if [ -d "libiq_build" ]; then
    echo "Removing libiq_build directory ..."
    rm -rf libiq_build
else
    echo "libiq_build directory does not exist"
fi

for file in _libiq.cpython*; do
    if [ -f "$file" ]; then
        echo "Removing compiled Python module $file ..."
        rm "$file"
    fi
done

cd ./src
for cxx_file in *.cxx; do
    if [[ $cxx_file == *_wrap.cxx ]]; then
        echo "Removing $cxx_file file generated by SWIG ..."
        rm "$cxx_file"

        py_file="${cxx_file%_wrap.cxx}.py"
        if [ -f "$py_file" ]; then
            echo "Removing $py_file file generated by SWIG ..."
            rm "$py_file"
        else
            echo "SWIG-generated $py_file file does not exist"
        fi
    fi
done
cd ..

cd ./examples
if [ -f "libiq.py" ]; then
    echo "Removing libiq.py file generated by SWIG that is inside examples directory..."
    rm "libiq.py"
fi
for file in _libiq.cpython*; do
    if [ -f "$file" ]; then
        echo "Removing compiled Python module $file ..."
        rm "$file"
    fi
done
cd ..
