name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-22.04
    if: ${{github.repository == 'wineslab/libiq' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install and upgrade pip
      run: python3 -m pip install --upgrade pip
    - name: Install build dependencies
      run: pip install --upgrade setuptools build hatch wheel pytest
    - name: Build a binary wheel and a source tarball
      run: ./build.sh
    - name: Install dist
      run: |
        pip install dist/libiq-*.tar.gz
        pip install libiq[all]
    - name: Test with pytest
      run: |
        cd docs
        pytest test_libiq.py